### ISSUE TITLE
could not connect with keys

### ISSUE THREAD

**Issue by manuks** [corneldamian/APNs#2]
openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert pub.pem -key pri.pem -CAfile entrust_2048_ca.cer

 works, but these are not working with the code

```
logerr("dial tls url", defaultConfig.gateway)
conn, err := tls.Dial("tcp", defaultConfig.gateway, conf)
if err != nil {
    logerr("dial tls err", err)
    return err
} 
```

 gives the following error
2015/04/17 19:24:37 apns.go:254: A failed push service is going to be revived
2015/04/17 19:24:37 apns.go:270: dial tls url%!(EXTRA string=gateway.sandbox.push.apple.com:2195)
2015/04/17 19:24:38 apns.go:270: dial tls err%!(EXTRA *errors.errorString=EOF)

Any clue?

**Comment by corneldamian** [comment]
can u do a simple go test program with dial to see if it can connect?

**Comment by corneldamian** [comment]
this error is printed exactly after the you start it? or after a time? 
Apple is closing the connection after a while.
EOF means that the apple closed the connection.

**Comment by manuks** [comment]
See my question in stackoverflow http://stackoverflow.com/questions/29714397/go-tls-connection-to-apple-push-notification-server-is-not-working

**Comment by corneldamian** [comment]
If you can give me the certificates i can do some tests. (You can invalidate the certificates after that)

**Comment by corneldamian** [comment]
what version of go are u using?

**Comment by manuks** [comment]
it is go1.4.2 windows/amd64

**Comment by corneldamian** [comment]
can you do this test on a linux machine?

**Comment by manuks** [comment]
Got the same EOF error on tls.Dial.
I will create another certificate/key pair and try with that.

**Comment by manuks** [comment]
I think it is something related to the certificate.
It is working with another certificate/key pair.
Sorry to bother you. You can close the issue.
